<a href="https://colab.research.google.com/github/aaron-v19/practice/blob/main/tensormath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
tensora=torch.tensor([1,2,3,4,5])
print(tensora)
tensorb=torch.tensor([6,7,8,9,10])
print(tensorb)

tensor([1, 2, 3, 4, 5])
tensor([ 6,  7,  8,  9, 10])


In [3]:
tensora+tensorb

tensor([ 7,  9, 11, 13, 15])

In [4]:
tensora*tensorb

tensor([ 6, 14, 24, 36, 50])

In [5]:
torch.sub(tensora,tensorb)

tensor([-5, -5, -5, -5, -5])

In [6]:
torch.mul(tensora,tensorb)

tensor([ 6, 14, 24, 36, 50])

In [7]:
tensora/tensorb

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [8]:
tensorb%tensora

tensor([0, 1, 2, 1, 0])

In [9]:
torch.remainder(tensora,tensorb)

tensor([1, 2, 3, 4, 5])

In [10]:
torch.pow(tensora,tensorb)


tensor([      1,     128,    6561,  262144, 9765625])

In [11]:
tensora.add_(tensorb)

tensor([ 7,  9, 11, 13, 15])

In [15]:
tensorb=tensora+tensorb
tensorb

tensor([34, 43, 52, 61, 70])